### ISSUE TITLE
Move from cbor to borc library

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/oisp-sdk-js#18]
node-cbor has a bug for large binary data types

**Comment by srware** [comment]
I have moved to borc on the development branch ready for testing.

**Comment by wagmarcel** [comment]
@srware almost :-)
When you are changing the package.json anyway, can you please move borc from  "devDependencies" to "dependencies" section?
The test fails because borc is not installed. I know that old " cbor" was in the same place. I investigated the reason why the test runs with cbor in devDependencies but not with borc. Result: cbor dependencies  is also installed by the test dependencies
https://github.com/Open-IoT-Service-Platform/platform-launcher/blob/facc13521a23a403ed2780b13a98864ca26f8025/tests/package.json#L22
which is bad. So best solution is to move borc to dependencies.

**Comment by srware** [comment]
Wow, that's super dumb. I obviously missed that in the original PR. I'll fix it now :)

**Comment by wagmarcel** [comment]
OK - seems to work. cf https://github.com/Open-IoT-Service-Platform/platform-launcher/pull/149
