### ISSUE TITLE
deviceToken/userToken inconsistency

### ISSUE THREAD

**Issue by oguzcankirmemis** [Open-IoT-Service-Platform/oisp-sdk-js#25]
There is a naming scheme inconsistency. For example:

- /api/devices/{deviceId} uses deviceToken
- /api/accounts/{accountId}/devices/{deviceId} uses userToken
- /api/accounts/{accountId}/cmpcatalog uses userToken
- /api/cmpcatalog uses userToken (!)

**Comment by srware** [comment]
Should be fixed in development now.
